---
- name: Disable SSH password auth
  linefile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: Restart SSH Daemon

- meta: flush_handlers
